##################### 应用配置
spring:
  application:
    ########### 应用名称
    name: config-server
  cloud:
    ########## 配置中心
    config:
      server:
        ########## git管理配置
        git:
          ########  配置git仓库位置
          uri: https://github.com/kevin-gm/spring-cloud-config
          ########  配置仓库路径下的相对搜索位置，可以配置多个
          searchPaths: /
          ########  访问git仓库的用户名
          username: li460982475.gm@gmail.com
          ########  访问git仓库的用户密码
          password: lgq--455718225

######## 端口配置
server:
  port: 7001