spring:
  ###  数据源相关配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boottest?characterEncoding=utf-8
    username: root
    password: kevin
  ###  JPA相关配置
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: prod
  ###  Thymeleaf模板引擎相关配置
  thymeleaf:
    prefix: classpath:/web/views/
    cache: false
  mvc:
    ###  favicon开关配置，默认为true，可以将自己的favicon.ico图标放置在类路径根目录
    favicon:
      enabled: true
###  日志相关配置
logging:
  ###  指定日志文件存放路径
  file: D:/logs/boot-test.log
  level:
    org:
      springframework:
        web: debug
###  容器配置
server:
  ###  指定服务端口，默认8080
  port: 8080
  ###  指定访问路径，默认为“/”
  context-path: /boot
  ###  Session过期配置，单位为秒
  session:
    timeout: 1800
  ###  Tomcat配置
  tomcat:
    ###  编码配置，默认UTF-8
    uri-encoding: UTF-8
  #ssl:
    #key-store: .keystore
    #key-store-password: 123456
    #key-store-type: JKS
    #key-alias: tomcat